import type { ApparelItem, Mission, NpcDef, SideMission, TrophyDef, WorldPoi } from "./types";

/** Warm Memphis dusk — brand green/gold are accents only. */
export const PAL = {
  asphalt: "#22201e",
  asphaltAlt: "#262320",
  lot: "#2a2623",
  lane: "rgba(184,166,120,0.22)",
  sidewalk: "#35302a",
  sidewalkAlt: "#3b352e",
  curb: "#4a4239",
  wall: "#2b2724",
  wallAlt: "#322c28",
  wallCool: "#26282c",
  roof: "#3d3630",
  roofEdge: "#6b5c4a",
  windowDark: "#1a1715",
  windowLit: "#f2c66a",
  grass: "#4a5c3a",
  grassTip: "#6d8250",
  shadow: "rgba(74,95,107,0.28)",
  shade: "#4a5f6b",
  label: "#c4b8a8",
  ink: "#0d0b0a",
  skyTop: "#3a2e24",
  skyBot: "#1a1612",
  river0: "#2a3840",
  river1: "#1a242c",
  accent: "#1db954",
  gold: "#d4af37",
} as const;

/** Bump to force the live preview to remount the world bake. */
export const ART_REV = 9;

export const TILE = 48;
export const WORLD_W = 64;
export const WORLD_H = 48;
export const WORLD_PX_W = WORLD_W * TILE;
export const WORLD_PX_H = WORLD_H * TILE;

export const PLAYER_SPEED = 168;
export const PLAYER_RUN = 268;

export const DEFAULT_SETTINGS = {
  master: 0.85,
  music: 0.42,
  sfx: 0.7,
  shake: true,
  rumble: true,
  cameraView: "third" as const,
};

export const APPAREL: ApparelItem[] = [
  {
    id: "starter_tee",
    name: "Starter Green Tee",
    price: 0,
    category: "top",
    color: "#1db954",
    description: "What Benji woke up in. In the sack we trust.",
  },
  {
    id: "classic_green",
    name: "Classic $ack Tee",
    price: 40,
    category: "top",
    color: "#16a34a",
    description: "The drop that put the city on notice.",
  },
  {
    id: "moneybag_hoodie",
    name: "Moneybag Hoodie",
    price: 90,
    category: "top",
    color: "#15803d",
    description: "Heavyweight fleece. Moneybag logo front and center.",
  },
  {
    id: "black_hoodie",
    name: "Midnight Hoodie",
    price: 85,
    category: "top",
    color: "#171717",
    description: "Black on black. Silent flex.",
  },
  {
    id: "fresh_jersey",
    name: "FRESH 38127 Jersey",
    price: 120,
    category: "top",
    color: "#0f766e",
    description: "Memphis zip. K Blanco co-sign energy.",
  },
  {
    id: "white_cap",
    name: "White Snapback",
    price: 35,
    category: "hat",
    color: "#f5f5f5",
    description: "SackReligious script. Keep it tilted.",
  },
  {
    id: "gold_chain",
    name: "Moneybag Chain",
    price: 150,
    category: "chain",
    color: "#d4af37",
    description: "Gold rope + pendant. Respect required.",
  },
  {
    id: "green_sweats",
    name: "Green Sweat Set",
    price: 110,
    category: "set",
    color: "#22c55e",
    description: "Full fit. Court to culture spot ready.",
  },
];

export const POIS: WorldPoi[] = [
  {
    id: "apartment",
    name: "Benji's Apartment",
    x: 5 * TILE,
    y: 7 * TILE,
    w: 4 * TILE,
    h: 4 * TILE,
    color: "#3f3f46",
    label: "HOME",
    district: "West Side",
  },
  {
    id: "store",
    name: "SackReligious HQ",
    x: 28 * TILE,
    y: 8 * TILE,
    w: 6 * TILE,
    h: 5 * TILE,
    color: "#2b2724",
    label: "HQ",
    district: "Midtown",
  },
  {
    id: "court",
    name: "901 Court",
    x: 11 * TILE,
    y: 29 * TILE,
    w: 8 * TILE,
    h: 7 * TILE,
    color: "#7c2d12",
    label: "BALL",
    district: "South Memphis",
  },
  {
    id: "neighborhood",
    name: "The Neighborhood",
    x: 46 * TILE,
    y: 10 * TILE,
    w: 5 * TILE,
    h: 4 * TILE,
    color: "#1e3a5f",
    label: "HOOD",
    district: "East Memphis",
  },
  {
    id: "downtown",
    name: "Downtown Memphis",
    x: 48 * TILE,
    y: 30 * TILE,
    w: 5 * TILE,
    h: 4 * TILE,
    color: "#1f2937",
    label: "DT",
    district: "Downtown",
  },
  {
    id: "culture",
    name: "The Culture Spot",
    x: 24 * TILE,
    y: 36 * TILE,
    w: 5 * TILE,
    h: 4 * TILE,
    color: "#322c28",
    label: "CULTURE",
    district: "South Main",
  },
  {
    id: "dropvan",
    name: "Drop Van",
    x: 38 * TILE,
    y: 21 * TILE,
    w: 3 * TILE,
    h: 2.5 * TILE,
    color: "#292524",
    label: "VAN",
    district: "Union Ave",
  },
  {
    id: "beale",
    name: "Beale Street",
    x: 18 * TILE,
    y: 19 * TILE,
    w: 8 * TILE,
    h: 3 * TILE,
    color: "#3d3630",
    label: "BEALE",
    district: "Beale",
  },
  {
    id: "pyramid",
    name: "The Pyramid",
    x: 54 * TILE,
    y: 4 * TILE,
    w: 6 * TILE,
    h: 6 * TILE,
    color: "#1c1917",
    label: "PYRAMID",
    district: "Harbor",
  },
  {
    id: "river",
    name: "Mississippi River",
    x: 1 * TILE,
    y: 42 * TILE,
    w: 14 * TILE,
    h: 4 * TILE,
    color: "#1e3a5f",
    label: "RIVER",
    district: "Riverfront",
  },
];

export const STREETS: { name: string; axis: "x" | "y"; tile: number }[] = [
  { name: "BEALE ST", axis: "y", tile: 20 },
  { name: "UNION AVE", axis: "y", tile: 6 },
  { name: "POPLAR AVE", axis: "y", tile: 34 },
  { name: "3RD ST", axis: "x", tile: 16 },
  { name: "FRONT ST", axis: "x", tile: 34 },
  { name: "HIGHLAND", axis: "x", tile: 50 },
];

export function createDropDayMission(): Mission {
  return {
    id: "drop_day",
    title: "The Drop Day",
    chapter: "CHAPTER 01",
    activeStep: 0,
    complete: false,
    steps: [
      {
        id: "wake",
        label: "Leave the apartment",
        description: "Drop Day is live. Step into Memphis.",
        target: "apartment",
        kind: "goto",
        reward: 10,
        done: false,
      },
      {
        id: "link_k",
        label: "Link up with K Blanco",
        description: "Hit SackReligious HQ and talk to K.",
        target: "store",
        kind: "talk",
        reward: 25,
        done: false,
      },
      {
        id: "pickup",
        label: "Pick up the drop",
        description: "Secure the new drop at the van.",
        target: "dropvan",
        kind: "pickup",
        reward: 40,
        done: false,
      },
      {
        id: "hood",
        label: "Move product — Neighborhood",
        description: "Connect with the real ones in the hood.",
        target: "neighborhood",
        kind: "deliver",
        reward: 50,
        done: false,
      },
      {
        id: "dt",
        label: "Move product — Downtown",
        description: "Downtown vibes. More supporters.",
        target: "downtown",
        kind: "deliver",
        reward: 50,
        done: false,
      },
      {
        id: "culture",
        label: "Move product — Culture Spot",
        description: "Last stop. The brand grows.",
        target: "culture",
        kind: "deliver",
        reward: 60,
        done: false,
      },
      {
        id: "ball",
        label: "Ball up for respect",
        description: "Hit the 901 Court. Score 8 points.",
        target: "court",
        kind: "basketball",
        reward: 45,
        done: false,
      },
      {
        id: "return",
        label: "Return to HQ",
        description: "Mission complete. Report back to K Blanco.",
        target: "store",
        kind: "return",
        reward: 100,
        done: false,
      },
    ],
  };
}

export function createSideMissions(): SideMission[] {
  return [
    {
      id: "pickup_kings",
      title: "Pickup Kings",
      description: "Score 16 in a single run at 901 Court.",
      reward: 80,
      done: false,
      kind: "score",
      target: "court",
      need: 16,
    },
    {
      id: "full_fit",
      title: "Full Fit",
      description: "Own four pieces from the HQ wall.",
      reward: 60,
      done: false,
      kind: "own",
      need: 4,
    },
    {
      id: "city_tour",
      title: "City Tour",
      description: "Talk to every local on the map.",
      reward: 70,
      done: false,
      kind: "talk",
      need: 6,
    },
    {
      id: "sunset_river",
      title: "Sunset at the River",
      description: "Walk the Mississippi riverfront.",
      reward: 35,
      done: false,
      kind: "visit",
      target: "river",
    },
    {
      id: "pyramid_pic",
      title: "Pyramid Flex",
      description: "Stand at the Pyramid and take it in.",
      reward: 40,
      done: false,
      kind: "visit",
      target: "pyramid",
    },
    {
      id: "beale_night",
      title: "Beale After Dark",
      description: "Hit Beale Street once the lights come on.",
      reward: 45,
      done: false,
      kind: "visit",
      target: "beale",
    },
  ];
}

export const TROPHIES: TrophyDef[] = [
  { id: "first_steps", name: "First Steps", description: "Leave the apartment on Drop Day.", rank: "bronze" },
  { id: "family", name: "Welcome to the Family", description: "Link with K Blanco at HQ.", rank: "bronze" },
  { id: "baller", name: "Baller", description: "Score 8 at the 901 Court.", rank: "silver" },
  { id: "drop_day", name: "Drop Day", description: "Finish the main mission.", rank: "gold" },
  { id: "fresh_fit", name: "Fresh Fit", description: "Buy your first apparel drop.", rank: "bronze" },
  { id: "deep_pockets", name: "Deep Pockets", description: "Hold $400 $ackdollars.", rank: "silver" },
  { id: "court_king", name: "Court King", description: "Score 20 in one basketball run.", rank: "gold" },
  { id: "city_legend", name: "901 Legend", description: "Reach 40 Respect.", rank: "gold" },
  { id: "night_owl", name: "Night Owl", description: "Be out after 20:00.", rank: "bronze" },
  { id: "full_closet", name: "Closet Heavy", description: "Own every piece on the wall.", rank: "platinum" },
];

export const NPCS: NpcDef[] = [
  {
    id: "k_blanco",
    name: "K Blanco",
    x: 30.5 * TILE,
    y: 10.5 * TILE,
    color: "#f5d0a9",
    dialogue: [
      "Welcome to the family. Glad you made it.",
      "In the sack, we trust. You ready for Drop Day?",
      "Shop the wall, move the product, grow the brand.",
    ],
    missionTalk: "Benji. Lock in. Grab the drop from the van, hit three spots, then bounce back.",
    isKBlanco: true,
  },
  {
    id: "supporter_1",
    name: "Local Supporter",
    x: 48 * TILE,
    y: 12 * TILE,
    color: "#a3a3a3",
    dialogue: [
      "You Benji? Heard SackReligious got that new drop.",
      "This city rocking with the brand heavy.",
    ],
  },
  {
    id: "downtown_fan",
    name: "901 Fan",
    x: 50 * TILE,
    y: 32 * TILE,
    color: "#e5e5e5",
    dialogue: ["Fresh fits only. Respect the movement.", "You got that energy, Benji."],
  },
  {
    id: "culture_host",
    name: "Culture Host",
    x: 26 * TILE,
    y: 38 * TILE,
    color: "#c4b8a8",
    dialogue: ["Culture spot is lit tonight.", "Drop sold through. Brand growing."],
  },
  {
    id: "court_coach",
    name: "Court OG",
    x: 13 * TILE,
    y: 31 * TILE,
    color: "#fdba74",
    dialogue: [
      "Court's open. Put up points, earn $ackdollars.",
      "Timing is everything. Let it fly at the peak.",
    ],
  },
  {
    id: "street_npc",
    name: "Memphis Local",
    x: 20 * TILE,
    y: 18 * TILE,
    color: "#c4b8a8",
    dialogue: ["Man, this city rockin' with the brand heavy.", "Pyramid looks different on Drop Day."],
    wander: true,
  },
  {
    id: "beale_dj",
    name: "Beale DJ",
    x: 22 * TILE,
    y: 21 * TILE,
    color: "#fbbf24",
    dialogue: ["Beale don't sleep. Brand either.", "When the neon hits, the city talks."],
    wander: true,
  },
];

export const TIPS = [
  "Hold Shift or the right face button to sprint the block.",
  "Release the shot in the green window for a swish.",
  "Streaks at the court pay extra $ackdollars.",
  "Press Start or Esc for the map, missions, and wardrobe.",
  "A DualSense or Xbox pad works — left stick to move, South to talk.",
  "Night on Beale hits different. Stay out after 20:00.",
  "Shop the wall at HQ. Fit changes how the city sees you.",
];

export const SAVE_KEY = "sackreligious-memphis-v2";
export const SAVE_KEY_LEGACY = "sackreligious-memphis-v1";
